version: "3.8"

services:
  postgres_lab7:
    image: postgres:17.2-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # том для данных
      - ./db_init_scripts:/docker-entrypoint-initdb.d # скрипты инициализации БД