version: "3.8"

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres_container
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # том для данных
      - ./db_init_scripts:/docker-entrypoint-initdb.d # скрипты инициализации БД